config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) {user.admin?} do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: "admin#show_post", as: 'admin_post'
  end

  get 'search', to: 'search#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :after_signup
  #posts/1/comments/4
  resources :posts do
    resources :comments
  end
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class: 'btn btn-primary' %>

app/views/admin/_nav_links.html.erb
<div class='container text-center'>
    <p>
        <%= link_to 'Admin', admin_path %><%= " > #{params[:action].capitalize}" unless params[:action].eql?("index") %>
    </p>
    <div class="btn-group">
        <%= render "admin/link", resource: Post %>
        <%= render "admin/link", resource: Comment %>
        <%= render "admin/link", resource: User %>
    </div>
</div>

app/views/admin/comments.html.erb
<div class='container'>
    <h1 class='text-center'>Administrator</h1>
    <%= render 'admin/nav_links' %>
</div>

app/views/admin/index.html.erb
<div class='container'>
    <h1 class='text-center'>Administrator</h1>
    <%= render 'admin/nav_links' %>
</div>

app/views/admin/posts.html.erb
<div class='container'>
    <h1 class='text-center'>Administrator</h1>
    <%= render 'admin/nav_links' %>

    <table class="table table-striped">
        <thead>
            <thead>
                <tr>
                    <th scope='col'>Id</th>
                    <th scope='col'>Post</th>
                    <th scope='col'>Author</th>
                    <th scope='col'>Comments</th>
                </tr>
            </thead>
            <tbody>
                <% @posts.each do |post| %>
                <tr>
                    <th  scope='row'><%= post.id %></th>
                    <td> <%= link_to post.title.truncate(15), admin_post_path(post) %> </td>
                    <td> <%= post.user.full_name %></td>
                    <td><%= pluralize(post.comments.size, "Comment") %></td>
                </tr>
                <% end %>
            </tbody>
        </thead>
    </table>
</div>

app/views/admin/show_post.html.erb
<div class="container">
    <h1 class='text-center'>Administrator</h1>
    <%= render 'admin/nav_links' %>
    <div class="text-center mt-5">
        <div class="btn-group">
            <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning' %>
            <%= button_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
        </div>
    </div>

    <div class="row mt-1">
        <p>
            <strong>Title:</strong> <%= @post.title %>
        </p>
    </div>
    
    <div class="row mt-1">
        <p>
            <strong>Views:</strong> <%= @post.views %>
        </p>
    </div>
    
    <div class="row mt-1">
        <p>
            <strong>Author:</strong>
            <%= "#{@post.user.email} | #{@post.user.full_name} | #{pluralize(@post.user.views, 'View')}" %>
        </p>
    </div>

    <div class="row mt-1">
        <p>
            <strong>Body:</strong> <%= @post.body %>
        </p>
    </div>

    <div class="row mt-1">
        <strong><%= pluralize(@post.comments.count, 'Comment') %> </strong>
        <% @post.comments.each do |comment| %>
            <div class="row mt-1">
                <%= comment.user.full_name %>
                <%= comment.body %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/users.html.erb
<div class='container'>
    <h1 class='text-center'>Administrator</h1>
    <%= render 'admin/nav_links' %>
</div>